#!/usr/bin/env groovy

node {
   stage('checkout') {
       checkout scm
   }
   
   stage('Installing Packages') {
      sh "java -version"
   }

   stage('packaging') {
       sh "mvn -U clean install"
   }

  // stage('Unit Test') {
  //     sh "mvn test"
  // }

   def doctorregVersion
   stage ('create Image Version'){
   symptomsVersion = sh (
   script: "date +'%Y-%m-%d-%H.%M'",
   returnStdout: true,
      )
  }

   def dockerImage
   stage('build docker') {
       sh "cp -R docker target/"
       sh "cp target/*.jar target/docker/"
       dockerImage = docker.build('telemed/symptoms', 'target/docker')
   }

   stage('publish docker') {
       docker.withRegistry('http://172.16.11.166:37719', 'telemed') {
           dockerImage.push "${symptomsVersion}"
         }
      }
      
   stage('delete docker Image') {
       sh "docker rmi telemed/symptoms"
       sh "docker rmi 172.16.11.166:37719/telemed/symptoms:${symptomsVersion}"
       }

   stage('run in 172.30.151.100') {
         sshagent (credentials: ['nsdl']) {
       sh "echo 'symptomsVersion=${symptomsVersion}' > .env"
       sh "scp -o StrictHostKeyChecking=no .env mosip@172.30.151.100:/var/workspace/telemedicine"
       sh "ssh -o StrictHostKeyChecking=no -l mosip 172.30.151.100 /var/workspace/telemedicine/helper/symptoms.sh"
         }
       }              
       
   }

